jobs:
  gpu_job:
    runs-on: ubuntu-latest  # GitHub Actions 运行在没有 GPU 的环境上
    container:
      image: nvidia/cuda:11.0-base  # 使用包含 CUDA 和 NVIDIA 支持的 Docker 镜像
    steps:
      - name: Check GPU availability
        run: |
          nvidia-smi
